@startuml
left to right direction

actor "User" as user
actor "Staff" as staff
actor "Admin" as admin

admin --|> staff

rectangle "Digital Banking API"{

    usecase "Register" as UC1
    usecase "Login" as UC2
    usecase "Create Account" as UC3
    usecase "View Own Account" as UC4
    usecase "Deposit" as UC5
    usecase "Withdraw" as UC6
    usecase "Transfer" as UC7
    usecase "View Own Transaction History" as UC8

    usecase "View Users" as UC9
    usecase "View Accounts" as UC10
    usecase "View Transactions" as UC11
    usecase "Block / Unblock Account" as UC12

    usecase "Manage Staff" as UC13
    usecase "Manage Roles" as UC14
    usecase "View Audit Log" as UC15

}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6
user --> UC7
user --> UC8

staff --> UC9
staff --> UC10
staff --> UC11
staff --> UC12

admin --> UC13
admin --> UC14
admin --> UC15

@enduml
